### ISSUE TITLE
First review of the ruby capstone group project

### ISSUE THREAD

**Issue by MattGomb** [MattGomb/catalog-of-my-things#20]
Dear Reviewer,

Here is the [link](https://github.com/MattGomb/catalog-of-my-things/projects/1) for our kanban board.

We assigned ourselves to each task, except for team member#3, because he has not accepted the invitation to the project yet, he is not in the call. But the tasks are assigned like this:
- Team member 1 is @jfoyarzo 
- Team member 2 is @MattGomb 
- (possible/probable) Team member 3 is @Dadadon

**Comment by Gambit142** [comment]
Hi @MattGomb @jfoyarzo , 

While you made a great effort in this project, I can't go ahead and review your code.

## Invalid Kanban  Review Request

- I understand that you are waiting for your partner to respond, but the right thing to do if your partner is not responding is to reach out to student success. Student success will try to reach out to your partner and give feedback on the collaboration status of your partner. 

#### Note: If you are to continue without your partner, resubmit this link with the feedback from student success that says you should continue without your partner. 👍 🙏 

Your Kanban Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by MattGomb** [comment]
I am submitting again, now with the 3rd group member added

**Comment by cynthiainga** [comment]
Hi @jfoyarzo  , @MattGomb & @Dadadon ,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![](https://user-images.githubusercontent.com/69011963/151541305-67f4f8e4-c79e-4f9d-a6cf-2c7efc3102c6.gif)

## Highlights

- [ ] Descriptive issue ✔️ 
- [ ] Setup correctly the Kanban board ✔️ 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
